### ISSUE TITLE
Add a `shouldUpdate` component method?

### ISSUE THREAD

**Issue by montlebalm** [rstacruz/decca#119]
I noticed you have https://github.com/rstacruz/deku-memoize, which creates a higher-order function that allows you to memoize renders. I would like to use it in conjunction with https://github.com/rstacruz/deku-stateful, but it seems like that's not possible due to the fact that the `shouldUpdate` logic is absorbed into `render`.

It seems reasonable to have a `shouldUpdate` function as part of the decca lib. Are you waiting to see which alternatives shake out as part of the deku v2 plans? It doesn't look like there's been much activity over there recently.

**Comment by rstacruz** [comment]
Stateful and memoize should play along nicely... There just has to be a
specific load order for it (I think it's `memoize(stateful(x))`). If it
doesn't, then those plugins would have to be fixed. But yeah, I'd like to
keep parity with deku as much as possible (though their api's have diverted
since deku changed some functions a bit!)

**Comment by montlebalm** [comment]
I imagine you'd want `shouldUpdate` to include next and previous state, but `stateful` can't inject the extra properties because the `shouldUpdate` function doesn't exist after it wraps the component. They might be made to work with some changes.

**Comment by rstacruz** [comment]
Hmm, I kind of remember setting them up so that there will be prev.state
and next.state if you use memoize(stateful(x)). Try that out
