### ISSUE TITLE
[Question] is the input has 1-on-1 mapping with the state (not like deku) ?

### ISSUE THREAD

**Issue by borisirota** [rstacruz/decca#205]
Hi, there is a [bug in `deku`](https://github.com/anthonyshort/deku/issues/170) where the input isn't reflecting the state, if the state hasn't changed and the user changed the value of the input. For example, when not allowing some characters.

What is the case in `decca` for this scenario ?

**Comment by rstacruz** [comment]
I think it will behave as Deku's if I understand the issue correctly.

**Comment by borisirota** [comment]
I'll try to explain the issue better :)

Let say you want some input to remain empty so you set it's value in the state to be empty string and set the input's value to be that field

```
const state = {
  field: ''
}
...
function render ({ ... field ... }) {
  return <input value={field}/>
}
```

My question is, if a user types characters inside the input, will it be seen inside the input (even though the field value is still empty string) or the input will remain empty even though the user is typing ?

I'm expecting it to remain empty because it should reflect the state without side effects and the bug inside `deku` is that the value changes regardless the state's value.

**Comment by rstacruz** [comment]
Ah: yes, it behaves like Deku would in this case. I think that's the expectation, too, because how else would the user be typing in the field? Deka and Deku doesn't manage the state of a DOM element's properties (eg, field.value or checkbox.checked or input selection), only it's attributes (eg, checkbox.setAttribute('checked')).

If you would like to block the user input to prevent the DOM properties from mutating, then you simply need to bind an 'oninput' handler. You can even make this propagate changes back to your store (which will propagate back to your form), though I recommend that to be done on an 'onchange' instead to prevent messing up your cursor/selection state.
